/* 参考项目路由挂载(与参考 backend/server.js 一致) */
const router = require('express').Router();

router.use('/auth', require('./auth'));
router.use('/users', require('./users'));
router.use('/departments', require('./departments'));
router.use('/teams', require('./teams'));
router.use('/customers', require('./customers'));
router.use('/contracts', require('./contracts'));
router.use('/purchases', require('./purchases'));
router.use('/projects', require('./projects'));
router.use('/suppliers', require('./suppliers'));
router.use('/leaves', require('./leaves'));
router.use('/expenses', require('./expenses'));
router.use('/documents', require('./documents'));
router.use('/approvals', require('./approvals'));
router.use('/finance', require('./finance'));
router.use('/salary', require('./salary'));
router.use('/hr', require('./hr'));
router.use('/permissions', require('./permissions'));
router.use('/checkin', require('./checkin'));
router.use('/reports', require('./reports'));
router.use('/sales', require('./sales'));
router.use('/business-trips', require('./businesstrips'));
router.use('/dashboard', require('./dashboard'));
router.use('/announcements', require('./announcements'));
router.use('/contract-form', require('./contract_form'));
router.use('/flow-contract-new', require('./flow_contract_new'));
router.use('/flow-contract-change', require('./flow_contract_change'));
router.use('/flow-contract-end', require('./flow_contract_end'));
router.use('/flow-contract-borrow', require('./flow_contract_borrow'));
router.use('/flow-contract-void', require('./flow_contract_void'));
router.use('/contract-permissions', require('./contract_permissions'));
router.use('/contract-analytics', require('./contract_analytics'));
router.use('/contract-risk', require('./contract_risk'));
router.use('/contract-template', require('./contract_template'));
router.use('/partner-credit', require('./partner_credit'));
router.use('/fin-expense', require('./finance_expense'));
router.use('/fin-loan', require('./finance_loan'));
router.use('/fin-invoice', require('./finance_invoice'));
router.use('/fin-payment', require('./finance_payment'));
router.use('/fin-budget', require('./finance_budget'));
router.use('/fin-hook', require('./finance_hook'));
router.use('/fin-config', require('./finance_config'));
router.use('/fin-ledger', require('./finance_ledger'));
router.use('/fin-receivable', require('./finance_receivable'));
router.use('/trade-purchase', require('./trade_purchase'));
router.use('/trade-sales', require('./trade_sales'));
router.use('/trade-finance', require('./trade_finance'));
router.use('/trade-customer', require('./trade_customer'));
router.use('/trade-supplier', require('./trade_supplier'));
router.use('/trade-archive', require('./trade_archive'));
router.use('/att-archive', require('./att_archive'));
router.use('/system-settings', require('./system_settings'));

module.exports = router;
